# Generated by Django 5.1.1 on 2024-11-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('contact_num', models.CharField(max_length=25, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('user_role', models.CharField(max_length=50, verbose_name='User Role')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(max_length=100, verbose_name='Flight NUmber')),
                ('ticket_num', models.CharField(max_length=100, verbose_name='Ticket Number')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('seat_type', models.CharField(max_length=25, verbose_name='Seat Type')),
                ('boarded', models.CharField(max_length=25, verbose_name='Boarded')),
            ],
        ),
        migrations.CreateModel(
            name='BookedFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=100, verbose_name='Ticket Number')),
                ('departure', models.DateField(verbose_name='Departure Date')),
                ('arrival', models.DateField(verbose_name='Arrival Date')),
                ('departure_time', models.TimeField(null=True, verbose_name='Departure Time')),
                ('arrival_time', models.TimeField(null=True, verbose_name='Arrival Time')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('seat_num', models.CharField(max_length=10, verbose_name='Seat Number')),
                ('flight_num', models.CharField(max_length=50, verbose_name='Flight Number')),
                ('seat_type', models.CharField(max_length=50, verbose_name='Seat Type')),
                ('reference_num', models.CharField(max_length=100, verbose_name='Reference Number')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('payment_status', models.CharField(max_length=50, verbose_name='Payment Status')),
                ('payment_date', models.DateTimeField(verbose_name='Payment Date')),
                ('flight_status', models.CharField(max_length=50, verbose_name='Flight Status')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('flight_number', models.CharField(max_length=100, verbose_name='Flight Number')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('discount_usage', models.IntegerField(null=True, verbose_name='Discount Usage')),
                ('flight_type', models.CharField(max_length=50, verbose_name='Flight Type')),
                ('departure', models.DateField(verbose_name='Departure')),
                ('arrival', models.DateField(verbose_name='Arrival')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('departure_time', models.TimeField(null=True, verbose_name='Departure Time')),
                ('arrival_time', models.TimeField(null=True, verbose_name='Arrival Time')),
                ('return_time', models.TimeField(null=True, verbose_name='Return Time')),
                ('discounted_price', models.IntegerField(null=True, verbose_name='Discounted Price')),
                ('available_seats', models.IntegerField(null=True, verbose_name='Available Seats')),
            ],
        ),
    ]
