# Generated by Django 5.1.1 on 2024-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedflights',
            name='return_date',
            field=models.DateField(max_length=50, null=True, verbose_name='Return Date'),
        ),
    ]
