# Generated by Django 5.1.1 on 2024-12-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0002_bookedflights_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
