# Generated by Django 5.1.1 on 2024-12-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0006_account_id_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
