# Generated by Django 5.1.1 on 2025-01-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0008_useradditionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
