# Generated by Django 5.1.1 on 2025-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0011_ticketsales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsales',
            old_name='payment_ammount',
            new_name='payment_amount',
        ),
    ]
