# Generated by Django 5.1.1 on 2025-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0012_rename_payment_ammount_ticketsales_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsales',
            name='month',
            field=models.DateTimeField(null=True, verbose_name='Month'),
        ),
    ]
